### ISSUE TITLE
How do we run tests locally? 

### ISSUE THREAD

**Issue by rheaton** [citusdata/pg_auto_failover#443]
Hello,

I am a new contributor, and I am having a difficult time running the python tests and getting my machine set up. Is there documentation to help contributors write and run tests? 

Thanks,
Rachel

-------

Note:
I'm are on a mac Catalina 10.15

Steps tried:
1. Installed psycopg2 (On my computer, v 2.7.5 wouldn't install, so used v 2.8.6 and updated Pipfile) `pip install psycopg2`
1. `PIPENV_PIPFILE=test/Pipfile  pipenv install --python=$(which python)`
1. `make test`

```
sudo -E env "PATH=/Users/rheaton/.cargo/bin:/usr/local/opt/mysql@5.7/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/ruby/bin:/Users/rheaton/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/rheaton/workspace/core-services-wiki/scripts:/Users/rheaton/.fzf/bin:/usr/local/sbin:/usr/local/Cellar/postgresql/12.4/bin:/Users/rheaton/Library/Python/3.8/bin" USER=rheaton \
		/usr/local/bin/nosetests			\
		--verbose				\
		--nocapture				\
		--stop					\
		--where=tests
ERROR

======================================================================
ERROR: test suite for <module 'test_auth' from '/Users/rheaton/workspace/pg_auto_failover/tests/test_auth.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nose-1.3.7-py3.8.egg/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/local/lib/python3.8/site-packages/nose-1.3.7-py3.8.egg/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python3.8/site-packages/nose-1.3.7-py3.8.egg/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python3.8/site-packages/nose-1.3.7-py3.8.egg/nose/util.py", line 471, in try_run
    return func()
  File "/Users/rheaton/workspace/pg_auto_failover/tests/test_auth.py", line 12, in setup_module
    cluster = pgautofailover.Cluster()
  File "/Users/rheaton/workspace/pg_auto_failover/tests/pgautofailover_utils.py", line 48, in __init__
    self.vlan = network.VirtualLAN(networkNamePrefix, networkSubnet)
  File "/Users/rheaton/workspace/pg_auto_failover/tests/network.py", line 53, in __init__
    self._add_bridge(self.bridgeName, self.bridgeAddress, self.prefixLen)
  File "/Users/rheaton/workspace/pg_auto_failover/tests/network.py", line 96, in _add_bridge
    _remove_interface_if_exists(name)
  File "/Users/rheaton/workspace/pg_auto_failover/tests/network.py", line 255, in _remove_interface_if_exists
    with IPRoute() as ipr:
  File "/usr/local/lib/python3.8/site-packages/pyroute2/iproute/linux.py", line 127, in __init__
    super(RTNL_API, self).__init__(*argv, **kwarg)
  File "/usr/local/lib/python3.8/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 27, in __init__
    super(IPRSocketMixin, self).__init__(NETLINK_ROUTE, fileno=fileno,
  File "/usr/local/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 364, in __init__
    self.post_init()
  File "/usr/local/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 915, in post_init
    self._sock = config.SocketBase(AF_NETLINK,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 47] Address family not supported by protocol family

----------------------------------------------------------------------
Ran 0 tests in 0.131s

FAILED (errors=1)
make: *** [test] Error 1
```

Is this implying that the tests can't be run on OSX?

**Comment by DimCitus** [comment]
Hi @rheaton ; welcome to the project! I'm not sure if this is written down anywhere at the moment (hint: it could be your first contribution), the test suite needs to be run in a docker environment, where we can install a virtual network using Linux network namespaces, and later run `ifconfig down` and `ifconfig up` commands and things.

Once you have a docker thing available, try the two following commands:

```
$ make TEST=test_auth run-test
$ make TEST=test_multi_standbys run-test 2>&1 > /tmp/test.log && echo ok
```
