### ISSUE TITLE
Error running make run-test

### ISSUE THREAD

**Issue by soumyadeep2007** [citusdata/pg_auto_failover#491]
Hi,

When I try to run the tests on my **Ubuntu 20 workstation**, I encounter:

```
pivotal@station4:~/workspace/pg_auto_failover$ make run-test 
docker build				\
			\
	-t pg_auto_failover-test	\
	.
Sending build context to Docker daemon  8.338MB
Step 1/13 : FROM debian:bullseye-slim
 ---> 021f355ada2e
Step 2/13 : ENV PGDATA /var/lib/postgresql/data
 ---> Using cache
 ---> 6251e69aedbd
Step 3/13 : RUN apt-get update   && apt-get install -y --no-install-recommends     build-essential     ca-certificates     git     iproute2     libicu-dev     libkrb5-dev     libssl-dev     libedit-dev     libpam-dev     zlib1g-dev     libxml2-dev     libxslt1-dev     libselinux1-dev     make     openssl     pipenv     postgresql-12     postgresql-server-dev-12     python3-nose     python3 	python3-setuptools 	python3-psycopg2 	python3-pyroute2     sudo     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 35f8b490b2a2
Step 4/13 : RUN adduser --disabled-password --gecos '' docker
 ---> Using cache
 ---> 211a045692a3
Step 5/13 : RUN adduser docker sudo
 ---> Using cache
 ---> 785bf9fe918c
Step 6/13 : RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 ---> Using cache
 ---> c7420787aaa3
Step 7/13 : WORKDIR /usr/src/pg_auto_failover
 ---> Using cache
 ---> e23641629f57
Step 8/13 : COPY Makefile ./
 ---> Using cache
 ---> 7c6e9dda32cd
Step 9/13 : COPY ./src/ ./src
 ---> Using cache
 ---> 7ff6396883c1
Step 10/13 : RUN make -s clean && make -s install -j8
 ---> Using cache
 ---> 31c642cc4438
Step 11/13 : COPY ./tests/ ./tests
 ---> Using cache
 ---> 7c3216f474bb
Step 12/13 : USER docker
 ---> Using cache
 ---> 7d797572a8ff
Step 13/13 : ENV PATH $PATH:/usr/lib/postgresql/12/bin
 ---> Using cache
 ---> 77fa856118ce
Successfully built 77fa856118ce
Successfully tagged pg_auto_failover-test:latest
docker run					\
	--name pg_auto_failover-test		\
	--cap-add=SYS_ADMIN --cap-add=NET_ADMIN -ti --rm			\
	pg_auto_failover-test			\
	make -C /usr/src/pg_auto_failover test	\
	TEST=''
make: Entering directory '/usr/src/pg_auto_failover'
sudo -E env "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/12/bin" USER=docker \
	/usr/bin/nosetests3			\
	--verbose				\
	--nocapture				\
	--stop					\
	--where=tests
ERROR

======================================================================
ERROR: test suite for <module 'test_auth' from '/usr/src/pg_auto_failover/tests/test_auth.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python3/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/usr/src/pg_auto_failover/tests/test_auth.py", line 12, in setup_module
    cluster = pgautofailover.Cluster()
  File "/usr/src/pg_auto_failover/tests/pgautofailover_utils.py", line 48, in __init__
    self.vlan = network.VirtualLAN(networkNamePrefix, networkSubnet)
  File "/usr/src/pg_auto_failover/tests/network.py", line 62, in __init__
    with open(BRIDGE_NF_CALL_IPTABLES, "w") as f:
OSError: [Errno 30] Read-only file system: '/proc/sys/net/bridge/bridge-nf-call-iptables'

----------------------------------------------------------------------
Ran 0 tests in 0.080s

FAILED (errors=1)
make: *** [Makefile:64: test] Error 1
make: Leaving directory '/usr/src/pg_auto_failover'
make: *** [Makefile:85: run-test] Error 2

```

From my limited understanding and attempt at debugging the issue, it seems that docker mounts /proc as read-only for security reasons.

**Comment by jchampio** [comment]
Ignoring `EROFS` in the call stack seems to "work", but it's not clear what changed in Docker to cause this to start failing...

**Comment by soumyadeep2007** [comment]
w/ @jchampio 
Docker versions on which the above reproduces: 

Ubuntu 20: Docker version 19.03.13, build 4484c46d9d
Mac Mojave 10.14.6, Docker version: 2.5.0.0

**Comment by rheaton** [comment]
+1 experiencing the same issue
