### ISSUE TITLE
segfault pg_autoctl drop node --destroy

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#663]
```
Core was generated by `pg_autoctl drop node --destroy'.
Program terminated with signal SIGQUIT, Quit.
#0  0x00007f14854b0a2a in unlink () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007f14854b0a2a in unlink () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffc01205610 in ?? ()
#2  0x0000565412a752cf in rmtree ()
#3  0x0000565412a752b0 in rmtree ()
#4  0x0000565412a752b0 in rmtree ()
#5  0x0000565412a04f1c in ?? ()
#6  0x0000565412a04caa in cli_drop_local_node ()
#7  0x0000565412a08cd5 in ?? ()
#8  0x0000565412a6bcfd in commandline_run ()
#9  0x0000565412a6bdb9 in commandline_run ()
#10 0x0000565412a6bdb9 in commandline_run ()
#11 0x0000565412a3c4a1 in main ()
```

**Comment by DimCitus** [comment]
Which version are you using? release, from git, etc... also, how to reproduce? There is nothing I can do with the information shared here unfortunately. Please re-open with more information if this is still an issue.
